#Specify the CPU request and limit
#In args we are questing or 2 cpu which is beyond te limit for failure
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: cpu-example
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"  #1 or 1000m == 1 core cpu, 0.5 == 500m, 0.1 == 100m
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
---
#lets specify the CPU limit more than the node
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: cpu-example
spec:
  containers:
  - name: cpu-demo-ctr-2
    image: vish/stress
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"
    args:
    - -cpus
    - "2"